apiVersion: apps/v1
kind: Deployment
metadata:
        name: api-deployment
spec:
        replicas: 2
        template:
                metadata:
                        name: api
                        labels:
                                app: api
                spec:
                        containers:
                                - name: api-container
                                  image: dockersamples/k8s-wordsmith-api
                                  ports:
                                          - containerPort: 8080
        selector:
                matchLabels:
                        app: api
